# POST http://127.0.0.1:8000/login/ 
# content-type: application/json

# {
#     "name": "sample",
#     "time": "Wed, 21 Oct 2015 18:27:50 GMT"

# }


POST http://127.0.0.1:8000/login/ 
content-type: application/json
{
    "username": "Yes", "password": "Pass1234!", "email":"sample@mail.com"
}


POST http://127.0.0.1:8000/test_token/ 
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}