# Generated by Django 5.0.2 on 2024-02-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tree_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytree',
            name='color',
        ),
        migrations.AlterField(
            model_name='tree',
            name='long',
            field=models.FloatField(),
        ),
    ]
