# Generated by Django 5.0.2 on 2024-02-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_mytree_color_alter_tree_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
