# Generated by Django 5.0.2 on 2024-02-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_tree_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='name',
            new_name='gattung',
        ),
        migrations.AddField(
            model_name='tree',
            name='pflanzjahr',
            field=models.IntegerField(default='1', max_length=5),
            preserve_default=False,
        ),
    ]
