# Generated by Django 5.0.2 on 2024-02-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tree_gebiet_tree_strasse_alter_tree_pflanzjahr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='pflanzjahr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
