# Generated by Django 5.0.2 on 2024-02-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_tree_pflanzjahr'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gattung', models.CharField(max_length=255)),
                ('pflanzjahr', models.CharField(max_length=255)),
                ('gebiet', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
