# Generated by Django 5.0.2 on 2024-02-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_geodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
