# Generated by Django 5.0.2 on 2024-02-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_geodata_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTree',
        ),
    ]
