# Generated by Django 5.0.2 on 2024-02-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_mytree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
            ],
        ),
    ]
