# Generated by Django 5.0.2 on 2024-02-29 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mitarbeiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aktion', models.CharField(max_length=50)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.geodata')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mitarbeiter')),
            ],
        ),
    ]
