# Generated by Django 4.2.10 on 2024-03-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auftrag'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='is_water',
            field=models.BooleanField(default=False),
        ),
    ]
