# Generated by Django 4.2.10 on 2024-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_geodata_is_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='last_watered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
