# Generated by Django 4.2.10 on 2024-03-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_geodata_last_watered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geodata',
            old_name='is_water',
            new_name='is_watered',
        ),
    ]
