# Generated by Django 5.0.2 on 2024-02-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('lat', models.TextField()),
                ('long', models.TextField()),
                ('is_water', models.IntegerField()),
            ],
        ),
    ]
