# Generated by Django 5.0 on 2024-02-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
    ]
